{ inputs, pkgs, ... }:

{
  home.packages = [
    pkgs.brightnessctl
    pkgs.wl-clipboard
    pkgs.gtk-engine-murrine
    pkgs.gh
    pkgs.zip
    pkgs.wl-gammactl
    pkgs.unzip
    pkgs.eza
    pkgs.cliphist
    pkgs.fuzzel
    pkgs.rofi
    pkgs.grim
    pkgs.slurp
    pkgs.hyprshot
    pkgs.swww
    pkgs.playerctl
    pkgs.pavucontrol
    pkgs.telegram-desktop
    pkgs.libnotify
    pkgs.jq
    inputs.zen-browser.packages.${pkgs.system}.default
    pkgs.hyprpanel
    pkgs.fastfetch
    pkgs.neovide
    pkgs.swayosd
    pkgs.legcord
    pkgs.btop
    pkgs.htop
    pkgs.rquickshare
    pkgs.enlightenment.ephoto
    pkgs.mpv
    pkgs.lazygit
    pkgs.wf-recorder
    pkgs.waypaper
    pkgs.nautilus
    pkgs.power-profiles-daemon
    pkgs.polkit_gnome
    pkgs.hyprsunset
  ];
}
