{pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    (vimPlugins.nvim-treesitter.withPlugins (plugins: [
      # Combine allGrammars with explicitly listed plugins if needed
      # (tree-sitter.allGrammars) ++ [ ... ]
      tree-sitter.allGrammars
      tree-sitter-c
      tree-sitter-cpp
      tree-sitter-dockerfile
      tree-sitter-fish
      tree-sitter-go
      tree-sitter-html
      tree-sitter-svelte
      tree-sitter-json
      tree-sitter-lua
      tree-sitter-nix
      tree-sitter-sql
      tree-sitter-python
      tree-sitter-r
      tree-sitter-dockerfile
      tree-sitter-java
      tree-sitter-regex
      tree-sitter-rust
      tree-sitter-toml
      tree-sitter-vim
      tree-sitter-yaml
      tree-sitter-toml
    ]))
    neovim
    wget
    alejandra
    lemminx
    nil
    svelte-language-server
    gopls
    nixd
    gnumake
    mesonlsp
    eza
    fish
    starship
    sassc
    ccls
    sqls
    dockerfile-language-server-nodejs
    jdt-language-server
    google-java-format
    vscode-langservers-extracted
    llvmPackages_19.clang-unwrapped
    gcc14
    libgcc
    typescript-language-server
    sass
    lua54Packages.luarocks_bootstrap
    stylua
    typescript
    nodejs-slim_22
    fish-lsp
    python312Packages.python-lsp-server
    pyright
    rust-analyzer
    marksman
    tailwindcss-language-server
    bash-language-server
    shfmt
    prettierd
    lua-language-server
    yarn
    pnpm
    gnumake
    cmake
    ninja
    ntfs3g
    libgdiplus
    polkit
    tree-sitter
    pciutils
    vulkan-tools
    cloudflare-warp
    android-tools
    dynamips
    ubridge
    busybox
    inetutils
    docker
    libvirt
    python3
    virt-viewer
    git
    p11-kit
    openssl
    gh
    lftp
		cloudflared
		sops
		age
  ];
}
