{
  imports = [
    ./fish/fish.nix
    ./hypr/hyprland.nix
    ./kitty/kitty.nix
    ./neovim/neovim.nix
    ./btop/btop.nix
    ./lazygit/lazygit.nix
    ./mpv/mpv.nix
    ./wlogout/wlogout.nix
    ./rofi/rofi.nix
    ./htop/htop.nix
    ./fuzzel/fuzzel.nix
    ./eza/eza.nix
    ./fastfetch/fastfetch.nix
    ./yazi/yazi.nix
    ./wofi/wofi.nix
    ./foot/foot.nix
    ./spicetify/spicetify.nix
		./xonsh/xonsh.nix
  ];
}
