#!/bin/sh

STATUS_FILE="/tmp/hyprsunset_mode_status"
ICONS="$HOME/.config/hypr/scripts/light.png"

is_running() {
	pgrep "$1" >/dev/null 2>&1
}

if [[ -f "$STATUS_FILE" ]]; then
	MODE=$(cat "$STATUS_FILE")
else
	MODE="--normal"
fi

case "$MODE" in
"--sunset")
	notify-send -a "hyprsunset" "Hyprsunset" "Starting hyprsunset sunset mode..." -i "$ICONS"
	/usr/bin/hyprsunset -t 3000k &
	NEXT_MODE="--mid-sunset"
    ;;
"--mid-sunset")
	notify-send -a "hyprsunset" "Hyprsunset" "Starting hyprsunset mid-sunset mode..." -i "$ICONS"
	/usr/bin/hyprsunset -t 4500k &
	NEXT_MODE="--vibrant"
	;;
"--vibrant")
	notify-send -a "hyprsunset" "Hyprsunset" "Starting hyprsunset vibrant mode..." -i "$ICONS"
	/usr/bin/hyprsunset -t 10000k &
	NEXT_MODE="--normal"
	;;
"--normal")
	notify-send -a "hyprsunset" "Hyprsunset" "Starting hyprsunset normal mode..." -i "$ICONS"
	/usr/bin/hyprsunset -t 6600k &
	NEXT_MODE="--sunset"
	;;
esac

sleep 1
if is_running "hyprsunset"; then
	notify-send -a "hyprsunset" "Hyprsunset" "hyprsunset $MODE mode started successfully." -i "$ICONS"
else
	notify-send -a "hyprsunset" "Hyprsunset" "Error: Failed to start hyprsunset $MODE mode." -i "$ICONS"   
fi

echo "$NEXT_MODE" >"$STATUS_FILE"
