#!/bin/sh
swww kill
swww init

# swww img $wall

# You can also specify outputs:
# swww img -o wallpaper1 $wall

# Control how smoothly the transition will happen and/or it's frame rate
# For the step, smaller values = more smooth. Default = 20
# For the frame rate, default is 30.
swww img $HOME/Pictures/wallpaper/moonred-samurai.png --transition-bezier 1,.01,0,1.05 --transition-duration 2.1 --transition-type grow --transition-fps 60 --transition-pos top-right
