{pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    vim
    lftp
    zed-editor-fhs
    wget
    poppler_utils
    libreoffice
    ntfs3g
    proton-pass
    vulkan-tools
    libgdiplus
    winetricks
    polkit
    ciscoPacketTracer8
    tree-sitter
    proton-ge-custom
    libgcc
    libGL
    libGLU
    pciutils
    blesh
    onlyoffice-desktopeditors
    ffmpeg
    pcsx2
    apacheHttpd
    nemo-with-extensions
    vulkan-tools
    vmware-workstation
    cloudflare-warp
    android-tools
    udiskie
    udisks
    wineWowPackages.waylandFull
    winetricks
    carlito
    jflap
    netbeans
    gparted
    linux-wifi-hotspot
    dynamips
    wireshark
    ubridge
    busybox
    inetutils
    docker
    libvirt
    python3
    upower
    upower-notify
    virt-viewer
  ];
}
